[package]
name = "ps"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "ps"
path = "src/lib.rs"

[dependencies]
log = "0.4.22"
modular-bitfield = "0.11.2"